

const routes = {
    home: '/',
    login: '/login',
    register: '/register',
    listCampaigns: '/list-campaigns',
    listCampaignsAdmin: '/manage-campaigns',
    campaigns: '/campaigns',
    campaignDetail: '/campaign/:campaignId',
    profile: '/profile',
    overviewPublisher: '/overview',
    overviewAdvertiser: '/overview',
    overviewAdmin: '/overview',
    unauthorized: '/unauthorized',
    publisherConversion: '/conversions',
    statistic: '/statistic',
    createCampaign: '/campaign/create',
    createLinkStep1: '/create-link/step1',
    createLinkStep2: '/create-link/step2',
    createLinkStep3: '/create-link/step3',
    createLinkStep4: '/create-link/step4',
    revenue: '/revenue',
    // list: '/list',
    trafficReport: '/traffic-report',
    listPublisherAmin: '/list-publisher',
    listPublisherAdvertiser: '/list-publisher',
    manageLink: '/manage-link',
    linkOfCampaign: '/list-link',
    conversionDetail: '/conversion-detail/:linkId',
    vnpaySuccess: '/overview/vnpay/success', 
    vnpayFailed: '/overview/vnpay/failed',
    shop: '/shop',
    listAccount: '/list-account',
}

export default routes;